In [2]:
import pandas as pd

In [4]:
dfVoiceWorks = pd.read_csv("../data/raw/person_voice_works.csv")
dfDetails = pd.read_csv("../data/raw/person_details.csv")
dfAnimeWorks = pd.read_csv("../data/raw/person_anime_works.csv")
dfAltNames = pd.read_csv("../data/raw/person_alternate_names.csv")

# Cleaning the data
### Person details df
##### Removing columns that are not needed

In [11]:
dfDetails = dfDetails.drop(columns=["url",
                                    "website_url",
                                    "image_url",
                                    "given_name",
                                    "family_name",
                                    "birthday"],
                           errors="ignore")
dfDetails = dfDetails[dfDetails["name"].notna()]

In [14]:
dfDetails

       person_mal_id               name  favorites        relevant_location
0                  1      Tomokazu Seki       6219          Berlin, Germany
1                  2    Tomokazu Sugita      47666         Los Angeles, USA
2                  3     Satsuki Yukino       1777            Madrid, Spain
3                  4         Aya Hirano      18374            Paris, France
4                  5   Kenichi Suzumura       5176             Osaka, Japan
...              ...                ...        ...                      ...
76694          90011   Nanako Kishimoto          0            Mumbai, India
76695          90012              Pamon          0             Tokyo, Japan
76696          90013       Tomoru Emoto          0             Tokyo, Japan
76697          90014             Hirari          0            Paris, France
76698          90015  Daisuke Taniguchi          0  Cape Town, South Africa

[76697 rows x 4 columns]

### Person alt names

In [20]:
dfAltNames = dfAltNames[dfAltNames["alt_name"].notna()]
dfAltNames

       person_mal_id             alt_name
0                  1         Seki Mondoya
1                  1                 門戸 開
2                  1         Monto Hiraku
3                  3                 雪野五月
4                 10        Kevin Hatcher
...              ...                  ...
20460          89567              Sydsnap
20461          89567  Queen of Degeneracy
20462          89826                   陳浩
20463          89842              Chidori
20464          89842                 Nobu

[20447 rows x 2 columns]

### Voice Works

In [21]:
dfVoiceWorks

        person_mal_id        role  anime_mal_id  character_mal_id  language
0                   1        Main         55830              2514  Japanese
1                   1  Supporting         60602              2822  Japanese
2                   1  Supporting         59229            140499  Japanese
3                   1  Supporting         60427            275856  Japanese
4                   1  Supporting         62067            190335  Japanese
...               ...         ...           ...               ...       ...
489511          89839  Supporting         40111            274622  Mandarin
489512          89840  Supporting         60544            266412  Mandarin
489513          89841  Supporting         60544            266416  Mandarin
489514          89842  Supporting         36896            279922  Japanese
489515          89952  Supporting         60260            279778  Japanese

[489516 rows x 5 columns]

### People works in anime industry

In [23]:
dfAnimeWorks

        person_mal_id                     position  anime_mal_id
0                   1       Theme Song Performance          3080
1                   1    Inserted Song Performance         15699
2                   1  Theme Song Performance (OP)           247
3                   1       Theme Song Performance           258
4                   1  Theme Song Performance (ED)         34825
...               ...                          ...           ...
458086          89951         In-Between Animation         11001
458087          89951                Key Animation         55092
458088          89951     Key Animation (eps 4, 9)         20053
458089          89951                Key Animation         50553
458090          89965          Music Not Yet Aired         62579

[458091 rows x 3 columns]

### Saving

In [24]:
dfDetails.to_csv("../data/cleaned/people_details.csv", index=False)
dfVoiceWorks.to_csv("../data/cleaned/people_voice_works.csv", index=False)
dfAltNames.to_csv("../data/cleaned/people_alternate_names.csv", index=False)
dfAnimeWorks.to_csv("../data/cleaned/people_anime_works.csv", index=False)