In [1]:
import pandas as pd

In [2]:
mapping = {
    'Congo (Kinshasa)': 'Democratic Republic of the Congo',
    'Congo (Brazzaville)': 'Republic of the Congo',
    'US': 'United States of America',
    'USA': 'United States of America',
    'United States': 'United States of America',
    'Tanzania': 'United Republic of Tanzania'
}

### Profiles df

In [3]:
dfProfiles = pd.read_csv("../data/raw/profiles.csv")

##### Changing NaN values

In [4]:
dfProfiles.drop_duplicates()

dfProfiles["gender"] = dfProfiles["gender"].fillna("Unknown")
dfProfiles["username"] = dfProfiles["username"].fillna("Unknown")

dfProfiles["birthday"] = pd.to_datetime(dfProfiles["birthday"], errors="coerce")
dfProfiles["birthday"] = dfProfiles["birthday"].fillna(pd.NaT)

dfProfiles["joined"] = pd.to_datetime(dfProfiles["joined"], errors="coerce")
dfProfiles["joined"] = dfProfiles["joined"].fillna(pd.NaT)

dfProfiles['location'] = dfProfiles['location'].replace(mapping)

dfProfiles["watching"] = pd.to_numeric(dfProfiles["watching"], errors="coerce").fillna(0).astype(int)
dfProfiles["completed"] = pd.to_numeric(dfProfiles["completed"], errors="coerce").fillna(0).astype(int)
dfProfiles["on_hold"] = pd.to_numeric(dfProfiles["on_hold"], errors="coerce").fillna(0).astype(int)
dfProfiles["dropped"] = pd.to_numeric(dfProfiles["dropped"], errors="coerce").fillna(0).astype(int)
dfProfiles["plan_to_watch"] = pd.to_numeric(dfProfiles["plan_to_watch"], errors="coerce").fillna(0).astype(int)

dfProfiles

,username,gender,birthday,location,joined,watching,completed,on_hold,dropped,plan_to_watch
0,ishikawas,Unknown,NaT,South Korea,NaT,0,0,0,0,0
1,CKK2,Unknown,NaT,United States of America,2018-12-01,3,182,15,0,405
2,--------788,Female,NaT,Mexico,2022-10-04,1,64,0,0,1
3,potatoaris,Unknown,NaT,Spain,2018-10-02,5,1,0,0,4
4,Rinrintan,Unknown,NaT,Japan,2019-05-12,20,311,40,16,34
...,...,...,...,...,...,...,...,...,...,...
337150,ariyanroy04,Unknown,NaT,United States of America,2021-03-30,35,130,0,0,489
337151,ariyanvk18,Male,NaT,Turkey,2022-01-24,7,101,1,12,21
337152,ariyoskz,Unknown,NaT,Germany,2022-07-07,1,155,2,11,15
337153,arizima23,Female,1998-06-23,Spain,2019-03-15,15,64,0,4,4
337154,arizkim,Unknown,NaT,South Africa,2020-12-07,7,38,1,0,33

In [5]:
dfProfiles.to_csv("../data/cleaned/users_profiles.csv", index=False)
dfProfiles = None

### Ratings df
##### Note: heavy file

In [ ]:
dfRatings = pd.read_csv("../data/raw/ratings.csv")

In [7]:
dfRatings = dfRatings.drop(columns=["is_rewatching"])
dfRatings["username"] = dfRatings["username"].fillna("Unknown")
dfRatings = dfRatings[dfRatings["num_watched_episodes"] < 2000]
dfRatings

              username  anime_id         status  score  num_watched_episodes
0          --------788     30276       watching      7                     3
1          --------788     28851      completed      7                     1
2          --------788     41168      completed      7                     1
3          --------788     22199      completed     10                    24
4          --------788     16498      completed     10                    25
...                ...       ...            ...    ...                   ...
124298352      arizkim     52305  plan_to_watch      0                     0
124298353      arizkim      4224  plan_to_watch      0                     0
124298354      arizkim     54790  plan_to_watch      0                     0
124298355      arizkim     53835  plan_to_watch      0                     0
124298356      arizkim     33352  plan_to_watch      0                     0

[124294775 rows x 5 columns]

In [8]:
dfRatings.to_csv("../data/cleaned/users_ratings.csv", index=False)
dfRatings = None

### Favs df

In [9]:
dfFavs = pd.read_csv("../data/raw/favs.csv")

In [10]:
dfFavs.drop_duplicates()
dfFavs = dfFavs[dfFavs["username"].notna()]

dfFavs

            username   fav_type      id
0          ishikawas      anime   45649
1          ishikawas      anime   38680
2          ishikawas      anime     795
3          ishikawas      anime   37510
4          ishikawas      anime     820
...              ...        ...     ...
4178742  vincent0607  character     497
4178743  vincent0607  character  118739
4178744  vincent0607  character  188177
4178745  vincent0607  character  141354
4178746  vincent0607  character  195178

[4178743 rows x 3 columns]

In [11]:
dfFavs.to_csv("../data/cleaned/users_favs.csv")
dfFavs = None