In [45]:
import matplotlib.pyplot as plt
import pandas as pd
import geopandas as gpd
import seaborn as sns
import plotly.express as px
from matplotlib.colors import LogNorm

In [46]:

dfAnime = pd.read_csv("../data/cleaned/anime.csv")
cols = ["score", "rank", "year"]
dfAnime = dfAnime[dfAnime[cols].ne(0).all(axis=1)]
dfAnime

,mal_id,title,type,status,score,scored_by,rank,popularity,members,favorites,...,score_1_votes,score_2_votes,score_3_votes,score_4_votes,score_5_votes,score_6_votes,score_7_votes,score_8_votes,score_9_votes,score_10_votes
10,873,.hack//Roots,TV,Finished Airing,6.85,36216.0,5197.0,2718,76863,235,...,262.0,370.0,675.0,1660.0,3794.0,6623.0,10344.0,6780.0,3266.0,2445.0
11,48,.hack//Sign,TV,Finished Airing,6.94,86861.0,4745.0,1393,191204,1456,...,775.0,1028.0,1808.0,4281.0,8876.0,14844.0,23210.0,17070.0,8766.0,6208.0
12,298,.hack//Tasogare no Udewa Densetsu,TV,Finished Airing,6.55,36190.0,6928.0,2864,70526,139,...,290.0,431.0,860.0,2007.0,4691.0,8028.0,10007.0,5661.0,2681.0,1541.0
19,58985,0-saiji Start Dash Monogatari,TV,Finished Airing,5.43,2530.0,12703.0,6424,12263,24,...,185.0,151.0,202.0,351.0,555.0,528.0,297.0,114.0,50.0,100.0
20,60425,0-saiji Start Dash Monogatari Season 2,TV,Finished Airing,5.63,1080.0,12053.0,9660,4376,10,...,41.0,30.0,61.0,89.0,261.0,227.0,154.0,154.0,28.0,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28902,37976,Zombieland Saga,TV,Finished Airing,7.50,250375.0,2050.0,463,523409,3323,...,868.0,940.0,2005.0,4920.0,12495.0,28724.0,72298.0,76836.0,33379.0,17931.0
28904,40174,Zombieland Saga Revenge,TV,Finished Airing,7.99,94201.0,707.0,1163,232624,1621,...,218.0,126.0,308.0,815.0,2368.0,6190.0,20186.0,33187.0,19394.0,11424.0
28906,1249,"Zone of the Enders: Dolores, I",TV,Finished Airing,6.92,4578.0,4846.0,6137,13757,39,...,34.0,41.0,81.0,161.0,412.0,755.0,1403.0,975.0,456.0,261.0
28932,7808,Zukkoke Knight: Don De La Mancha,TV,Finished Airing,5.71,343.0,11688.0,13954,1238,3,...,24.0,18.0,16.0,12.0,67.0,34.0,92.0,53.0,8.0,18.0
28950,59421,Zutaboro Reijou wa Ane no Moto Konyakusha ni D...,TV,Finished Airing,7.37,15624.0,2562.0,3621,46157,182,...,54.0,40.0,95.0,255.0,854.0,2303.0,5545.0,3919.0,1598.0,1235.0

#### The graph shows us 2 behavior to look at:
1. The correlation between total_users and the score it's almost linear. This makes sense because low scored anime won't have an high number of total users
2. The second behavior looks normal too, where as the total_users grows the dots become smaller, meaning they have an higher position of popularity among the others anime

In [47]:
fig = px.scatter(dfAnime, x = "total_users", y = "score", size = "popularity", hover_name= "title")
fig.update_xaxes(range = [0, 500000])
fig.show()

#### The graph is made mainly by 3 parts
1. The head, where  we can see that the line descending rapidly. A very little amount of anime can claim a score greater than 8.5
2. The body, where the score lowers slowly meaning that even at 6k rank we have a good quality anime.
3. The tail, where at the very last places of the rankings we can see that there is only a little amount of anime got a score lower than 4.5

In [48]:
fig = px.scatter(dfAnime, x = "rank", y = "score", hover_name= "title")
fig.show()

In [49]:
fig = px.density_heatmap(dfAnime, x = "year", y = "score", hover_name= "title", nbinsx=50 )
fig.update_xaxes(range = [1960, 2026])
fig.show()

In [50]:
dfRec = pd.read_csv("../data/cleaned/recommendation.csv")
dfRec

        mal_id  recommended_anime_id
0         3269                   317
1         3269                  6922
2         3269                   299
3         3269                  3446
4         3269                  5681
...        ...                   ...
105244   31245                  1689
105245   31245                 35434
105246   31245                 31798
105247   31245                 21995
105248   36305                 42897

[105249 rows x 2 columns]

In [51]:
dfRec = dfRec.merge(dfAnime[["mal_id", "title"]], left_on = "mal_id", right_on = "mal_id")
dfRec = dfRec.rename(columns = {
    "title": "from"
})

In [52]:
dfRec = dfRec.merge(dfAnime[["mal_id", "title", "popularity"]], left_on = "recommended_anime_id", right_on = "mal_id")
dfRec = dfRec.rename(columns = {
    "title": "to"
})

In [53]:
dfRec

,mal_id_x,recommended_anime_id,from,mal_id_y,to,popularity
0,873,11757,.hack//Roots,11757,Sword Art Online,6
1,873,17265,.hack//Roots,17265,Log Horizon,139
2,873,6702,.hack//Roots,6702,Fairy Tail,56
3,873,52347,.hack//Roots,52347,"Shangri-La Frontier: Kusoge Hunter, Kamige ni ...",612
4,873,1482,.hack//Roots,1482,D.Gray-man,311
...,...,...,...,...,...,...
74007,1249,93,"Zone of the Enders: Dolores, I",93,Kidou Senshi Gundam SEED,1458
74008,1249,1086,"Zone of the Enders: Dolores, I",1086,Kenran Butou Sai: The Mars Daybreak,4971
74009,59421,60157,Zutaboro Reijou wa Ane no Moto Konyakusha ni D...,60157,Kanpekisugite Kawaige ga Nai to Konyaku Haki s...,2743
74010,59421,51552,Zutaboro Reijou wa Ane no Moto Konyakusha ni D...,51552,Watashi no Shiawase na Kekkon,735
74011,59421,22101,Zutaboro Reijou wa Ane no Moto Konyakusha ni D...,22101,Soredemo Sekai wa Utsukushii,798

In [54]:
dfTemp = (
    dfRec
    .groupby("to")
    .size()
    .reset_index(name = "num")
    .sort_values("num", ascending=False)
    .head(100)
)
dfTemp

                                   to  num
2114       Mahou Shoujo Madoka★Magica  244
3190             Shinseiki Evangelion  234
594   Code Geass: Hangyaku no Lelouch  230
1076                          Gintama  211
3460       Tengen Toppa Gurren Lagann  198
...                               ...  ...
3811                        Working!!   94
1792                 Kimetsu no Yaiba   94
491                 Cardcaptor Sakura   94
241      Azumanga Daiou The Animation   94
300                         Barakamon   93

[100 rows x 2 columns]

In [57]:
dfTemp = dfTemp.merge(dfRec[["to", "popularity"]], on = "to")

In [64]:
fig = px.scatter(dfTemp, x = "to", y = "num", hover_name="to", size = "popularity")
fig.update_xaxes(
    tickfont = dict(size = 7),
    tickangle = 45
)
fig.show()