In [5]:
import pandas as pd

# Cleaning the data
### 1. Details Df
##### We are ignoring the columns that contains an high number of empty values and columns that are not important for the sake of the analysis

In [6]:
dfDetails = pd.read_csv("../data/raw/details.csv")

dfDetails.drop_duplicates()
dfDetails = dfDetails.drop(columns=["title_japanese",
                                    "url",
                                    "start_date",
                                    "end_date",
                                    "synopsis",
                                    "studios",
                                    "demographics",
                                    "season",
                                    "licensors",
                                    "explicit_genres",
                                    "streaming"],
                           errors = "ignore")

dfDetails["type"] = dfDetails["type"].fillna("Unknown")
dfDetails["rating"] = dfDetails["rating"].fillna("Unknown")

#dfDetails["score"] = dfDetails["score"].fillna(0)
#dfDetails["scored_by"] = dfDetails["scored_by"].fillna(0)
#dfDetails["rank"] = dfDetails["rank"].fillna(0)

#dfDetails["episodes"] = dfDetails["episodes"].fillna(0)
dfDetails["episodes"] = dfDetails["episodes"].astype("Int64")

#dfDetails["year"] = dfDetails["year"].fillna(0)
dfDetails["year"] = dfDetails["year"].astype("Int64")

dfDetails = dfDetails.rename(columns={"total": "total_users"})

dfDetails

,mal_id,title,image_url,type,status,score,scored_by,rank,popularity,members,favorites,genres,themes,source,rating,episodes,year,producers
0,59356,-Socket-,https://cdn.myanimelist.net/images/anime/1043/...,Movie,Finished Airing,NaN,NaN,17086.0,22507,195,0,['Comedy'],[],Original,G - All Ages,1,<NA>,['Nagoya Zokei University']
1,56036,......,https://cdn.myanimelist.net/images/anime/1057/...,Music,Finished Airing,6.53,503.0,NaN,15004,941,2,"['Horror', 'Supernatural']",['Music'],Original,PG-13 - Teens 13 or older,1,<NA>,[]
2,2928,.hack//G.U. Returner,https://cdn.myanimelist.net/images/anime/1798/...,OVA,Finished Airing,6.65,9745.0,6366.0,5056,22525,31,"['Adventure', 'Drama', 'Fantasy']",['Video Game'],Game,PG-13 - Teens 13 or older,1,<NA>,"['Bandai Visual', 'CyberConnect2']"
3,3269,.hack//G.U. Trilogy,https://cdn.myanimelist.net/images/anime/1566/...,Movie,Finished Airing,7.06,15373.0,4194.0,4215,34264,104,"['Action', 'Fantasy']",['Video Game'],Game,PG-13 - Teens 13 or older,1,<NA>,['Bandai Visual']
4,4469,.hack//G.U. Trilogy: Parody Mode,https://cdn.myanimelist.net/images/anime/10/86...,Special,Finished Airing,6.35,4317.0,8182.0,6696,11135,10,"['Comedy', 'Fantasy', 'Sci-Fi']","['Parody', 'Video Game']",Game,PG-13 - Teens 13 or older,1,<NA>,['Bandai Visual']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28950,59421,Zutaboro Reijou wa Ane no Moto Konyakusha ni D...,https://cdn.myanimelist.net/images/anime/1518/...,TV,Finished Airing,7.37,15624.0,2562.0,3621,46157,182,"['Drama', 'Romance']",[],Light novel,PG-13 - Teens 13 or older,12,2025,"['Studio Pierrot', 'Mainichi Broadcasting Syst..."
28951,31245,Zutto Mae kara Suki deshita. Kokuhaku Jikkou I...,https://cdn.myanimelist.net/images/anime/3/821...,Movie,Finished Airing,7.20,104106.0,3494.0,1077,249631,682,['Romance'],['School'],Music,PG-13 - Teens 13 or older,1,<NA>,"['Aniplex', 'Dentsu', 'Kadokawa Shoten', 'Movi..."
28952,36305,Zutto Mae kara Suki deshita. Kokuhaku Jikkou I...,https://cdn.myanimelist.net/images/anime/6/883...,Special,Finished Airing,7.17,10038.0,3664.0,4680,27334,34,['Romance'],['School'],Music,PG - Children,1,<NA>,['Aniplex']
28953,34895,Zutto Suki Datta,https://cdn.myanimelist.net/images/anime/1498/...,OVA,Finished Airing,5.68,1887.0,NaN,8916,5525,11,"['Drama', 'Hentai']",['School'],Manga,Rx - Hentai,2,<NA>,"['Queen Bee', 'Mediabank']"
28954,56606,Zutto Tomodachi,https://cdn.myanimelist.net/images/anime/1462/...,Music,Finished Airing,NaN,NaN,NaN,24773,124,0,[],['Music'],Original,G - All Ages,1,<NA>,['NHK']

In [7]:
dfDetails.to_csv("../data/cleaned/anime.csv", index = False)
dfDetails = None

### 2. Stats df
##### Same goes for the stats, ignoring columns that can be obtained with simple calculations or obtained in other ways

##### Decided to keep the score_x_votes to analyze better in the future§

In [8]:
dfStats = pd.read_csv("../data/raw/stats.csv")

dfStats = dfStats.drop(columns=dfStats.filter(regex="percentage$").columns)
dfStats.drop_duplicates()

cols = ["score_1_votes", "score_2_votes", "score_3_votes", "score_4_votes", "score_5_votes", "score_6_votes", "score_7_votes", "score_8_votes", "score_9_votes", "score_10_votes"]
dfStats[cols] = dfStats[cols].fillna(0)
dfStats[cols] = dfStats[cols].astype(int)

dfStats

,mal_id,watching,completed,on_hold,dropped,plan_to_watch,total,score_1_votes,score_2_votes,score_3_votes,score_4_votes,score_5_votes,score_6_votes,score_7_votes,score_8_votes,score_9_votes,score_10_votes
0,59356,7,146,4,20,20,197,2,0,3,6,25,33,19,2,0,1
1,56036,21,770,8,29,113,941,5,6,8,14,50,138,144,81,17,40
2,2928,451,14953,302,349,6472,22527,101,93,164,457,1184,2054,2709,1500,875,608
3,3269,726,22790,452,537,9762,34267,120,156,260,560,1270,2457,4157,3075,1919,1400
4,4469,241,6918,182,266,3528,11135,83,104,182,292,683,888,871,592,308,315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28950,59421,11349,17353,574,1440,15729,46445,54,40,95,255,854,2303,5545,3919,1598,1235
28951,31245,10332,140676,2989,1416,94249,249662,357,484,1011,2269,7199,15972,34370,24387,10480,7589
28952,36305,928,16119,388,243,9656,27334,48,28,78,182,773,1839,3258,2009,887,936
28953,34895,896,2387,375,356,1512,5526,116,80,102,172,337,437,280,170,68,125
28954,56606,4,83,2,15,20,124,3,1,1,4,22,15,7,1,0,4

In [9]:
dfStats.to_csv("../data/cleaned/anime_stats.csv", index = False)
dfStats = None

### 3. Recommendation df
##### Cleaning the recommendation by removing duplicates and eventual self recommendation

In [10]:
dfRecs = pd.read_csv("../data/raw/recommendations.csv")
dfRecs = dfRecs[dfRecs["mal_id"] != dfRecs["recommendation_mal_id"]]
dfRecs.drop_duplicates()

        mal_id  recommendation_mal_id
0         3269                    317
1         3269                   6922
2         3269                    299
3         3269                   3446
4         3269                   5681
...        ...                    ...
105244   31245                   1689
105245   31245                  35434
105246   31245                  31798
105247   31245                  21995
105248   36305                  42897

[105249 rows x 2 columns]

In [11]:
dfRecs = (
    dfRecs.groupby("mal_id")["recommendation_mal_id"]
    .agg(list)
    .reset_index()
)

In [12]:
dfRecs = dfRecs.rename(columns={"recommendation_mal_id": "recommended_anime_id"})
dfRecs

      mal_id                               recommended_anime_id
0          1  [205, 6, 889, 400, 20057, 2251, 4087, 2025, 91...
1          5  [4106, 21339, 122, 9135, 23279, 1796, 393, 522...
2          6  [1, 45, 25, 27, 267, 411, 4981, 24439, 297, 40...
3          7  [2025, 790, 13601, 270, 467, 150, 20053, 202, ...
4          8  [417, 136, 138, 28121, 249, 246, 129, 127, 479...
...      ...                                                ...
9028   61512                                            [22839]
9029   61595                           [38826, 37396, 433, 256]
9030   61672                                     [60521, 42192]
9031   61984                               [32281, 3701, 17121]
9032   62417                                     [57199, 42984]

[9033 rows x 2 columns]

##### Saving the normalized df

In [13]:
dfRecs.to_csv("../data/cleaned/anime_recommendation.csv", index = False)
dfRecs = None