In [61]:
import pandas as pd

# Cleaning the data
### Person details df
##### Removing columns that are not needed

In [62]:
dfDetails = pd.read_csv("../data/raw/person_details.csv")

In [63]:
dfDetails = dfDetails.drop(columns=["url",
                                    "website_url",
                                    "given_name",
                                    "family_name",
                                    "birthday"],
                           errors="ignore")
dfDetails = dfDetails[dfDetails["name"].notna()]

dfDetails

,person_mal_id,image_url,name,favorites,relevant_location
0,1,https://cdn.myanimelist.net/images/voiceactors...,Tomokazu Seki,6219,"Berlin, Germany"
1,2,https://cdn.myanimelist.net/images/voiceactors...,Tomokazu Sugita,47666,"Los Angeles, USA"
2,3,https://cdn.myanimelist.net/images/voiceactors...,Satsuki Yukino,1777,"Madrid, Spain"
3,4,https://cdn.myanimelist.net/images/voiceactors...,Aya Hirano,18374,"Paris, France"
4,5,https://cdn.myanimelist.net/images/voiceactors...,Kenichi Suzumura,5176,"Osaka, Japan"
...,...,...,...,...,...
76694,90011,https://cdn.myanimelist.net/img/sp/icon/apple-...,Nanako Kishimoto,0,"Mumbai, India"
76695,90012,https://cdn.myanimelist.net/img/sp/icon/apple-...,Pamon,0,"Tokyo, Japan"
76696,90013,https://cdn.myanimelist.net/img/sp/icon/apple-...,Tomoru Emoto,0,"Tokyo, Japan"
76697,90014,https://cdn.myanimelist.net/img/sp/icon/apple-...,Hirari,0,"Paris, France"
76698,90015,https://cdn.myanimelist.net/img/sp/icon/apple-...,Daisuke Taniguchi,0,"Cape Town, South Africa"

In [64]:
dfTemp = (
    dfDetails.groupby("person_mal_id")["relevant_location"]
    .agg(list)
    .reset_index()
)
dfTemp

       person_mal_id          relevant_location
0                  1          [Berlin, Germany]
1                  2         [Los Angeles, USA]
2                  3            [Madrid, Spain]
3                  4            [Paris, France]
4                  5             [Osaka, Japan]
...              ...                        ...
76587          90011            [Mumbai, India]
76588          90012             [Tokyo, Japan]
76589          90013             [Tokyo, Japan]
76590          90014            [Paris, France]
76591          90015  [Cape Town, South Africa]

[76592 rows x 2 columns]

In [65]:
dfTemp = dfTemp.merge(dfDetails[["person_mal_id", "image_url", "name", "favorites"]], on="person_mal_id")
dfTemp = dfTemp.drop_duplicates(subset=["person_mal_id"])
dfTemp

,person_mal_id,relevant_location,image_url,name,favorites
0,1,"[Berlin, Germany]",https://cdn.myanimelist.net/images/voiceactors...,Tomokazu Seki,6219
1,2,"[Los Angeles, USA]",https://cdn.myanimelist.net/images/voiceactors...,Tomokazu Sugita,47666
2,3,"[Madrid, Spain]",https://cdn.myanimelist.net/images/voiceactors...,Satsuki Yukino,1777
3,4,"[Paris, France]",https://cdn.myanimelist.net/images/voiceactors...,Aya Hirano,18374
4,5,"[Osaka, Japan]",https://cdn.myanimelist.net/images/voiceactors...,Kenichi Suzumura,5176
...,...,...,...,...,...
76692,90011,"[Mumbai, India]",https://cdn.myanimelist.net/img/sp/icon/apple-...,Nanako Kishimoto,0
76693,90012,"[Tokyo, Japan]",https://cdn.myanimelist.net/img/sp/icon/apple-...,Pamon,0
76694,90013,"[Tokyo, Japan]",https://cdn.myanimelist.net/img/sp/icon/apple-...,Tomoru Emoto,0
76695,90014,"[Paris, France]",https://cdn.myanimelist.net/img/sp/icon/apple-...,Hirari,0
76696,90015,"[Cape Town, South Africa]",https://cdn.myanimelist.net/img/sp/icon/apple-...,Daisuke Taniguchi,0

In [66]:
dfTemp.to_csv("../data/cleaned/actors_details.csv", index=False)
dfTemp = None
dfDetails = None

### Person alt names

In [67]:
dfAltNames = pd.read_csv("../data/raw/person_alternate_names.csv")

In [68]:
dfAltNames = dfAltNames[dfAltNames["alt_name"].notna()]
dfAltNames

       person_mal_id             alt_name
0                  1         Seki Mondoya
1                  1                 門戸 開
2                  1         Monto Hiraku
3                  3                 雪野五月
4                 10        Kevin Hatcher
...              ...                  ...
20460          89567              Sydsnap
20461          89567  Queen of Degeneracy
20462          89826                   陳浩
20463          89842              Chidori
20464          89842                 Nobu

[20447 rows x 2 columns]

In [69]:
dfAltNames.to_csv("../data/cleaned/actors_alternate_names.csv", index=False)

### Voice Works

In [70]:
dfVoiceWorks = pd.read_csv("../data/raw/person_voice_works.csv")

In [71]:
dfVoiceWorks

        person_mal_id        role  anime_mal_id  character_mal_id  language
0                   1        Main         55830              2514  Japanese
1                   1  Supporting         60602              2822  Japanese
2                   1  Supporting         59229            140499  Japanese
3                   1  Supporting         60427            275856  Japanese
4                   1  Supporting         62067            190335  Japanese
...               ...         ...           ...               ...       ...
489511          89839  Supporting         40111            274622  Mandarin
489512          89840  Supporting         60544            266412  Mandarin
489513          89841  Supporting         60544            266416  Mandarin
489514          89842  Supporting         36896            279922  Japanese
489515          89952  Supporting         60260            279778  Japanese

[489516 rows x 5 columns]

In [72]:
dfVoiceWorks.to_csv("../data/cleaned/actors_voice_works.csv", index=False)
dfVoiceWorks = None

### People works in anime industry

In [73]:
dfAnimeWorks = pd.read_csv("../data/raw/person_anime_works.csv")

In [74]:
dfAnimeWorks

        person_mal_id                     position  anime_mal_id
0                   1       Theme Song Performance          3080
1                   1    Inserted Song Performance         15699
2                   1  Theme Song Performance (OP)           247
3                   1       Theme Song Performance           258
4                   1  Theme Song Performance (ED)         34825
...               ...                          ...           ...
458086          89951         In-Between Animation         11001
458087          89951                Key Animation         55092
458088          89951     Key Animation (eps 4, 9)         20053
458089          89951                Key Animation         50553
458090          89965          Music Not Yet Aired         62579

[458091 rows x 3 columns]

In [75]:
dfAnimeWorks.to_csv("../data/cleaned/actors_anime_works.csv", index=False)
dfAnimeWorks = None