In [1]:
import pandas as pd
import sys
sys.path.append("./modules")
from modules.Cleaning import *
from modules.Functions import *

### Profiles df
- dropping duplicates
- filling na values
- normalizing nation names
- normalizing types

In [2]:
try:
    dfProfiles = pd.read_csv("../data/raw/profiles.csv")
except FileNotFoundError:
    print(f"File not found: ../data/raw/profiles.csv")
except pd.errors.EmptyDataError:
    print("The file is empty")
dfProfiles = clean_user_profiles(dfProfiles)
dfProfiles

,username,gender,birthday,location,joined,watching,completed,on_hold,dropped,plan_to_watch
0,ishikawas,Unknown,NaT,South Korea,NaT,0,0,0,0,0
1,CKK2,Unknown,NaT,United States of America,2018-12-01,3,182,15,0,405
2,--------788,Female,NaT,Mexico,2022-10-04,1,64,0,0,1
3,potatoaris,Unknown,NaT,Spain,2018-10-02,5,1,0,0,4
4,Rinrintan,Unknown,NaT,Japan,2019-05-12,20,311,40,16,34
...,...,...,...,...,...,...,...,...,...,...
337150,ariyanroy04,Unknown,NaT,United States of America,2021-03-30,35,130,0,0,489
337151,ariyanvk18,Male,NaT,Turkey,2022-01-24,7,101,1,12,21
337152,ariyoskz,Unknown,NaT,Germany,2022-07-07,1,155,2,11,15
337153,arizima23,Female,1998-06-23,Spain,2019-03-15,15,64,0,4,4
337154,arizkim,Unknown,NaT,South Africa,2020-12-07,7,38,1,0,33

Unluckily there is only 22 locations

In [3]:
dfProfiles["location"].unique()

<StringArray>
[             'South Korea', 'United States of America',
                   'Mexico',                    'Spain',
                    'Japan',                   'Turkey',
                'Indonesia',                'Argentina',
                   'France',                 'Thailand',
                  'Germany',                'Australia',
                    'China',                    'Italy',
           'United Kingdom',             'South Africa',
                    'Egypt',              'Philippines',
                    'India',                   'Canada',
                   'Brazil',                  'Vietnam']
Length: 22, dtype: str

In [4]:
save_csv(dfProfiles, "../data/cleaned/users_profiles.csv")
dfProfiles = None

### Ratings df
##### Note: heavy file, use nrows to reduce load
- filling na values
- removing outliers
- dropping not relevant columns

In [5]:
try:
    dfRatings = pd.read_csv("../data/raw/ratings.csv")
except FileNotFoundError:
    print(f"File not found: ../data/raw/ratings.csv")
except pd.errors.EmptyDataError:
    print("The file is empty")
dfRatings = clean_ratings(dfRatings)
dfRatings

              username  anime_id         status  score  num_watched_episodes
0          --------788     30276       watching      7                     3
1          --------788     28851      completed      7                     1
2          --------788     41168      completed      7                     1
3          --------788     22199      completed     10                    24
4          --------788     16498      completed     10                    25
...                ...       ...            ...    ...                   ...
124298352      arizkim     52305  plan_to_watch      0                     0
124298353      arizkim      4224  plan_to_watch      0                     0
124298354      arizkim     54790  plan_to_watch      0                     0
124298355      arizkim     53835  plan_to_watch      0                     0
124298356      arizkim     33352  plan_to_watch      0                     0

[124294775 rows x 5 columns]

In [6]:
save_csv(dfRatings, "../data/cleaned/users_ratings.csv")
dfRatings = None

### Favs df
- dropping duplicates
- dropping rows where username na

In [7]:
try:
    dfFavs = pd.read_csv("../data/raw/favs.csv")
except FileNotFoundError:
    print(f"File not found: ../data/raw/favs.csv")
except pd.errors.EmptyDataError:
    print("The file is empty")
dfFavs = clean_favorites(dfFavs)
dfFavs

            username   fav_type      id
0          ishikawas      anime   45649
1          ishikawas      anime   38680
2          ishikawas      anime     795
3          ishikawas      anime   37510
4          ishikawas      anime     820
...              ...        ...     ...
4178742  vincent0607  character     497
4178743  vincent0607  character  118739
4178744  vincent0607  character  188177
4178745  vincent0607  character  141354
4178746  vincent0607  character  195178

[4178743 rows x 3 columns]

In [8]:
save_csv(dfFavs, "../data/cleaned/users_favs.csv")
dfFavs = None